version: 2.1

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          name: "Restoring Cache"
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

  save_cache_cmd:
    steps:
      - save_cache:
          paths:
            - node_modules
            - dist
            - package.json
            - firebase.json
            - .firebaserc
          key: v1-dist-$CIRCLE_BRANCH-$CIRCLE_SHA1

  build_cmd:
    steps:
      - checkout
      - restore_cache_cmd
      - run: yarn install
      - run: yarn build
      - save_cache_cmd
      - run: yarn test:unit

  deploy_cmd:
    steps:
      - restore_cache:
          name: "Restoring Cache"
          key: v1-dist-$CIRCLE_BRANCH-$CIRCLE_SHA1

      - run:
          name: Showing Directory
          command: pwd
      - run:
          name: Looking in Directory
          command: ls -ltr
      - run:
          name: Deploying "master" to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

executors:
  docker-executor:
    docker:
      - image: circleci/node:10.8.0

jobs:
  build-job:
    executor: docker-executor
    working_directory: ~/repo
    steps:
      - build_cmd

  deploy-job:
    executor: docker-executor
    working_directory: ~/repo
    steps:
      - deploy_cmd

workflows:
  version: 2
  deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master


