version: 2.1

commands:
  restore_deps_cache_cmd:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

  restore_cache_cmd:
    steps:
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

  save_cache_cmd:
    steps:
      - save_cache:
          paths:
            - node_modules
            - dist
            - package.json
            - firebase.json
            - .firebaserc
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

  build_cmd:
    steps:
      - checkout
      # - restore_deps_cache_cmd
      # - run: yarn install
      # - run: yarn build
      - run:
          name: Looking in Directory
          command: ls -ltr

      - run:
          name: Finding tests in Directory
          command: find *tests/unit/**/*.spec.*

      - run:
          name: Keeping Build Url Artifact
          command: |
            mkdir ~/repo/tmp;
            cp *tests/unit/**/*.spec.* ~/repo/tmp/{{ .Environment.CIRCLE_PULL_REQUEST }};
          when: on_fail

      - store_artifacts:
          path: ~/repo/tmp

      # - save_cache_cmd
      # - run: yarn test:unit

  deploy_cmd:
    steps:
      - restore_cache_cmd

      - run:
          name: Showing Directory
          command: pwd
      - run:
          name: Install Firebase
          command: npm install --save-dev firebase-tools

      - run:
          name: Looking in Directory
          command: ls -ltr
      - run:
          name: Deploying "master" to Firebase
          command: yarn firebase-deploy -- --token=$FIREBASE_DEPLOY_TOKEN

executors:
  docker-executor:
    docker:
      - image: circleci/node:10.8.0

jobs:
  build-job:
    executor: docker-executor
    working_directory: ~/repo
    steps:
      - build_cmd

  deploy-job:
    executor: docker-executor
    working_directory: ~/repo
    steps:
      - deploy_cmd

  greeting:
    executor: docker-executor
    steps:
      - run:
          command: echo $GREETING_TEXT
          environment:
            GREETING_TEXT: "special thanks for the first day"

workflows:
  version: 2.1

  # commit:
  #   jobs:
  #     - greeting:
  #         context: "Daily build"
  #         filters:
  #           branches:
  #             only:
  #               - test

  daily:
    # triggers:
    #   - schedule:
    #       cron: "45,50 * * 6 0"
    #       filters:
    #         branches:
    #           only:
    #             - master
    jobs:
      - build-job
      # - hold:
      #     type: approval
      #     requires:
      #       - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only:
                - master
  # deploy:
  #   jobs:
  #     - build-job
  #     - greeting:
  #         requires:
  #           - build-job
  #     - hold:
  #         type: approval
  #         requires:
  #           - greeting
  #     - deploy-job:
  #         requires:
  #           - hold
  #         filters:
  #           branches:
  #             only: master
