version: 2.1

commands:
  restore_deps_cache_cmd:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

  restore_cache_cmd:
    steps:
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

  save_cache_cmd:
    steps:
      - save_cache:
          paths:
            - node_modules
            - dist
            - package.json
            - firebase.json
            - .firebaserc
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

  build_cmd:
    steps:
      - checkout
      - restore_deps_cache_cmd
      - run: yarn install
      - run: yarn build
      - save_cache_cmd
      - run: yarn test:unit

  deploy_cmd:
    steps:
      - restore_cache_cmd

      - run:
          name: Showing Directory
          command: pwd
      - run:
          name: Install Firebase
          command: npm install --save-dev firebase-tools
      - run:
          name: Looking in Directory
          command: ls -ltr
      - run:
          name: Deploying "master" to Firebase
          command: yarn firebase-deploy -- --token=$FIREBASE_DEPLOY_TOKEN

executors:
  docker-executor:
    docker:
      - image: circleci/node:10.8.0

jobs:
  build-job:
    executor: docker-executor
    working_directory: ~/repo
    steps:
      - build_cmd

  deploy-job:
    executor: docker-executor
    working_directory: ~/repo
    steps:
      - deploy_cmd

workflows:
  version: 2.1
  deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
